config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:show, :new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORIES = ['chinese', 'italian', 'japanese', 'french', 'belgian']
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :restaurant, presence: true
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # before_action :find_reataurant, only: [:show]
  def index
    @restaurants = Restaurant.all
  end

  def show
    sum = 0
    length = 0
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.reviews.last.nil?
      @rating = 'no ratings yet'
    else
      @restaurant.reviews.each do |review|
        sum += review.rating
        length += 1
      end
      @rating = sum / length
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  # def find_reataurant
  #   @restaurant = Restaurant.find(params[:id])
  # end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :find_restaurant

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Rubik:400,700&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
      </div>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<div class="d-flex align-items-end justify-content-between"><h1>Our restaurants</h1>
  <%= link_to "+Add a new restaurant",new_restaurant_path  %></div>
<% @restaurants.each do |restaurant| %>
  <%= link_to restaurant.name, restaurant_path(restaurant) %>
  <br>
  <img src="https://source.unsplash.com/random" alt="picture">


  <br>
<% end %>
<br>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>
 <%= simple_form_for(@restaurant) do |f| %>

  <% f.error_notification %>
  <% f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection: ['chinese', 'italian', 'japanese', 'french', 'belgian'] %>
  </div>

  <div class="form-actions btn btn-success text-white">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/show.html.erb
<h1 ><%= @restaurant.name %></h1>
<h3 ><%= @restaurant.category %> restaurant</h3>
<br>
<p><span class = 'name'>address:</span> <%= @restaurant.address %></p>
<p><span class="name">phone number:</span><%= @restaurant.phone_number %></p>


    <% if @rating.class == Integer   %>
      <span class ="name">rating: <% @rating.times do  %>⭐️</span>
      <% end %>
    <% else %>
    <span class ="name"> rating: </span><%= @rating %>



  <% end %>

  <br>
<p class = 'name'>reviews:</p>
<% @restaurant.reviews.each do |review| %>
  <p class = "container"><%= link_to review.content, restaurant_review_path(@restaurant) %></p>
<% end %>
<!-- <p><%#= @restaurant.reviews %></p> -->
<br>
<%= link_to "⃪ back to list ", restaurants_path %>|
<%= link_to "+add a review", new_restaurant_review_path(@restaurant) %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1 class = "text-center">Add a review</h1>
<%= simple_form_for([@restaurant, @review]) do |f| %>
  <% f.error_notification %>
  <% f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs rounded">
    <%= f.input :content%>
    <%= f.input :rating, input_html: { min: '0', step: '1', max: "5" }  %>
  </div>

  <div class="form-actions btn btn-success">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/show.html.erb
<h1><%= @restaurant.name %> </h1>
<% @review.rating.times do %>
  <%= "⭐️" %>
<% end %>
<p><%= @review.content %></p>

<%= link_to "⃪ back to restaurant",restaurant_path(@restaurant)  %>